---
- name: Install development packages
  apt:
    name:
      - nodejs
      - npm
      - python3-pip
      - openjdk-11-jdk
      - virtualbox
    state: present

- name: Install development snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop:
    - { name: 'code', classic: true }
    - { name: 'postman' }
    - { name: 'go', classic: true }
