---
- name: Install development packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - nodejs
      - npm
      - python3-pip
      - openjdk-11-jdk
      - mongodb-mongosh
      - virtualbox
      - vagrant
    state: present

- name: Install development snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop:
    - { name: 'code', classic: true }
    - { name: 'postman' }
    - { name: 'go', classic: true }

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
