---
- name: Install development packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - nodejs
      - npm
      - python3-pip
      - openjdk-11-jdk
      - mongodb-mongosh
      - virtualbox
      - vagrant
    state: present

- name: Download AWS CLI installer
  get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0755'

- name: Install unzip if not present
  apt:
    name: unzip
    state: present

- name: Unzip AWS CLI installer
  unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: yes

- name: Install AWS CLI
  command: "/tmp/aws/install"
  args:
    creates: "/usr/local/bin/aws"

- name: Install development snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop:
    - { name: 'code', classic: true }
    - { name: 'postman' }
    - { name: 'go', classic: true }

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes

- name: Enable docker service
  service:
    name: docker
    state: started
    enabled: yes
