---
- name: Copy background image
  copy:
    src: "{{ playbook_dir }}/files/backgrounds/wallpaper.png"
    dest: "{{ ansible_env.HOME }}/.local/share/backgrounds/"
    mode: '0644'

- name: Set background image (light mode)
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.png'"

- name: Set background image (dark mode)
  dconf:
    key: "/org/gnome/desktop/background/picture-uri-dark"
    value: "'file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.png'"

- name: Set screensaver image
  dconf:
    key: "/org/gnome/desktop/screensaver/picture-uri"
    value: "'file://{{ ansible_env.HOME }}/.local/share/backgrounds/wallpaper.png'"
