---
# Add repository keys
- name: Add repository keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop:
    - https://download.docker.com/linux/ubuntu/gpg
    - https://dl.google.com/linux/linux_signing_key.pub
    - https://www.mongodb.org/static/pgp/server-7.0.asc
    - https://packages.cloud.google.com/apt/doc/apt-key.gpg
    - https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823

# Add repositories from captured configuration
- name: Add APT repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: "{{ item.split(' ')[0] | replace('deb', '') | trim }}"
  loop:
    - "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    - "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
    - "deb [signed-by=/usr/share/keyrings/mongodb-org-7.0.gpg] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/7.0 multiverse"
    - "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    - "ppa:obsproject/obs-studio"

# Install base packages from captured configuration
- name: Install base packages
  apt:
    name:
      - arp-scan
      - awscli
      - btop
      - build-essential
      - cmake
      - copyq
      - curl
      - firewalld
      - fzf
      - git
      - gparted
      - guake
      - nmap
      - tree
      - vim
    state: present

# Install snap packages from captured configuration
- name: Install base snap packages
  community.general.snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic | default(false) }}"
    state: present
  loop:
    - { name: 'core' }
    - { name: 'core18' }
    - { name: 'core20' }
    - { name: 'firefox', classic: true }
    - { name: 'vlc' }
    - { name: 'keepassxc' }
